### PR TITLE
Fix use of linuxdeployqt

### PR DESCRIPTION
**Pull request by TheAssassin**

### CODE REVIEW

**Comment by TheAssassin** [comment]
@MIfeanyi you weren't patient enough on IRC, so here's a PR for you. You need a FHS-like structure, like the `make install` call sets up. You should just fix MilkyTracker's CMake config to install the desktop file and icon, then remove the workaround in `.travis.yml`.

Oh, by the way, next time check out https://workaround.org/getting-help-on-irc/...

**Comment by MIfeanyi** [comment]
cool

**Comment by TheAssassin** [comment]
You didn't want to merge it?

**Comment by MIfeanyi** [comment]
@TheAssassin  Like you said MT CMake should do the work. I'm not a Travis CI user so I was just playing with it. I resolved the issue I was having but thank you Honestly you'd be a better person than me to tackle issue 127 for Milkytracker. I just played around with it since no one else did.

**Comment by TheAssassin** [comment]
@MIfeanyi what I said is the CMake script should install the icon and desktop file. CMake can't package AppImages (yet).

**Comment by MIfeanyi** [comment]
I'm aware but the next build moves all this into its own script. The code your merging isn't there anymore

**Pull request closed without merging**
